#!/usr/bin/env bash
# Bash script to ping an IP address passed as an argument

if [ "$#" -eq 0 ]; then
    echo "Usage: $0 {IP_ADDRESS}"
else
    ip_address="$1"
    echo "PING $ip_address"
    ping -c 5 "$ip_address"
fi
