#!/usr/bin/env bash
# This task shows the use of ping command to  ping an IP address passed as an argument.
# Author: Eng Vincent.M.Karimi

if [ $1 == ""]
then 
	 echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
 else
	 ping -c 5 "$1"
fi
