#!/usr/bin/env bash
# Configures nginx server to listen on port 80

rm /etc/nginx/sites-enabled/default
sudo ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sudo service nginx restart
