#!/usr/bin/env bash
# This code prints the numbers 1 to 100 where it :
#            Displays FizzBuzz when the number is a multiple of 3 and 5
#            Displays Fizz when the number is multiple of 3
#            Displays Buzz when the number is a multiple of 5
#            Otherwise, displays the number in a list format
# Author: Eng Vincent.M.Karimi
for k in {1..100}
do
	if [ $((k % 3)) == 0 ] && [ $((k % 5)) == 0 ]
then 
    echo "FizzBuzz"
elif [ $((k % 5)) == 0 ] 
then
       echo "Buzz"
elif [ $((k % 3)) == 0 ]
then
      echo "Fizz"
else
         echo "$k"
fi
done
