#!/usr/bin/env bash
# This code checks if a file exists, if true whether it's empty and if it's a regular file
# Author: Eng Vincent.M.Karimi
if [ -e school ]
then
   echo "school file exists"
   if [ -s school ]
then
       echo "school file is not empty"
else
  echo "school file is empty"
fi
if [ -f school ]
then
       echo "school is a regular file"
fi
else
           echo "school file does not exist"
fi
