#!/bin/bash

# Change localhost IP to 127.0.0.2
sudo sed -i 's/127.0.0.1/127.0.0.2/g' /etc/hosts

# Change facebook.com IP to 8.8.8.8
sudo sed -i 's/facebook.com/8.8.8.8/g' /etc/hosts

# Display the updated hosts file
cat /etc/hosts

# Inform the user to revert changes if needed
echo "If you're running this script on a machine that you'll continue to use,"
echo "be sure to revert localhost to 127.0.0.1. Otherwise, a lot of things will stop working!"
